/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get or update the daemon config */
    get: operations["get_config"];
    /** Get or update the daemon config */
    put: operations["put_config"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate TOML config without persisting */
    post: operations["post_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List devices and reservations */
    get: operations["list_devices"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices/samples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get device memory samples */
    get: operations["get_device_samples"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get daemon listen addresses */
    get: operations["get_info"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get request metrics (time-bucketed) */
    get: operations["get_metrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/oneshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Create or list oneshot processes */
    get: operations["list_oneshots"];
    put?: never;
    /** Create or list oneshot processes */
    post: operations["post_oneshot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/oneshot/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get or delete a oneshot process */
    get: operations["get_oneshot"];
    put?: never;
    post?: never;
    /** Get or delete a oneshot process */
    delete: operations["delete_oneshot"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all services */
    get: operations["list_services"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get service detail */
    get: operations["service_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/command": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get launch command preview */
    get: operations["service_command"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable a service */
    post: operations["post_disable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/enable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enable a disabled service */
    post: operations["post_enable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get service logs (paginated) */
    get: operations["get_logs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/restart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restart a service */
    post: operations["post_restart"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a service */
    post: operations["post_start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/services/{name}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stop a service */
    post: operations["post_stop"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chat/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat completion (OpenAI-compatible proxy) */
    post: operations["chat_completions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Text completion (OpenAI-compatible proxy) */
    post: operations["completions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/embeddings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Embeddings (OpenAI-compatible proxy) */
    post: operations["embeddings"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available models (OpenAI-compatible) */
    get: operations["list_models"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description `{"error": {"code", "message", "type"}}`. The shared wire DTO; the
     *     daemon-side `ApiErrorCode` enum is the source of truth for which
     *     `code`, `message`, and `type` go together.
     */
    ApiError: {
      /** @description The nested body with the actual error metadata. */
      error: components["schemas"]["ApiErrorBody"];
    };
    /** @description Inner body of [`ApiError`]. */
    ApiErrorBody: {
      /**
       * @description Short slug identifying the error class. Clients may switch on
       *     these strings; the [`ApiErrorCodeSlug`] enum enumerates every
       *     value the daemon emits.
       */
      code: components["schemas"]["ApiErrorCodeSlug"];
      /** @description Human-readable error message. */
      message: string;
      /**
       * @description OpenAI's taxonomy — [`ApiErrorKind::InvalidRequestError`] for
       *     things the client could have avoided, [`ApiErrorKind::ServerError`]
       *     for daemon-side problems. Derived from the daemon's `ApiErrorCode`
       *     variant.
       */
      type: components["schemas"]["ApiErrorKind"];
    };
    /**
     * @description Stable wire slug identifying an error class. Clients may switch on
     *     these strings. The `Other` variant is a deserialization fallback so
     *     clients don't break when the daemon adds a new code before they're
     *     updated.
     *
     *     Variant names are serialised as `snake_case` strings (e.g.
     *     `ModelNotFound` → `"model_not_found"`) via `#[serde(rename_all)]`.
     *     The one exception is [`ApiErrorCodeSlug::InvalidRequest`], which
     *     serialises as `"invalid_request_error"` to match OpenAI's
     *     error-type taxonomy.
     * @enum {string}
     */
    ApiErrorCodeSlug:
      | "model_not_found"
      | "service_not_found"
      | "service_disabled"
      | "start_queue_full"
      | "start_failed"
      | "insufficient_vram"
      | "service_blocked"
      | "upstream_unavailable"
      | "proxy_internal"
      | "not_implemented"
      | "invalid_request_error"
      | "invalid_cursor"
      | "if_match_required"
      | "hash_mismatch"
      | "persist_failed"
      | "other";
    /**
     * @description OpenAI's error-type taxonomy. `InvalidRequestError` for anything the
     *     client could have avoided, `ServerError` for daemon-side problems.
     *     `Other` is a deserialization fallback.
     * @enum {string}
     */
    ApiErrorKind: "invalid_request_error" | "server_error" | "other";
    /**
     * @description `POST /v1/chat/completions` request envelope.
     *
     *     The daemon only interprets the `model` field; all other keys are
     *     forwarded verbatim to the upstream service.
     */
    ChatCompletionEnvelope: {
      [key: string]: unknown;
    } & {
      /** @description Model name (maps to an ananke service name). */
      model: string;
    };
    /**
     * @description `POST /v1/completions` request envelope.
     *
     *     The daemon only interprets the `model` field; all other keys are
     *     forwarded verbatim to the upstream service.
     */
    CompletionEnvelope: {
      [key: string]: unknown;
    } & {
      /** @description Model name (maps to an ananke service name). */
      model: string;
    };
    /** @description `GET /api/config` response body. */
    ConfigResponse: {
      /** @description Raw TOML content. */
      content: string;
      /** @description SHA-256 of `content`, base64-encoded; used as an `If-Match` value on PUT. */
      hash: string;
      /**
       * @description Whether the config file can be written to. `false` when the file
       *     is on a read-only store (e.g. NixOS-managed); the frontend should
       *     start the editor in read-only mode.
       */
      writable: boolean;
    };
    /** @description `POST /api/config/validate` request body. */
    ConfigValidateRequest: {
      /** @description Raw TOML to validate without persisting. */
      content: string;
    };
    /** @description `POST /api/config/validate` response body. */
    ConfigValidateResponse: {
      /** @description Structured validation errors (span-annotated where possible). */
      errors: components["schemas"]["ValidationError"][];
      /** @description `true` iff no errors were found. */
      valid: boolean;
    };
    /** @description `GET /api/info` response body. */
    DaemonInfoResponse: {
      /** @description The management API listen address (e.g. `"0.0.0.0:7071"`). */
      management_listen: string;
      /** @description The OpenAI-compatible API listen address (e.g. `"0.0.0.0:7070"`). */
      openai_listen: string;
    };
    /**
     * @description One device's share of a [`PlacementPreview`], with enough context to draw a
     *     utilisation bar: this service's share, what is already in use by everything
     *     else, and the device's total capacity.
     */
    DevicePlacement: {
      /**
       * Format: int64
       * @description Memory bytes this service reserves on the device — the pledge floor for a
       *     dynamic service.
       */
      bytes: number;
      /** @description Slot string: `"cpu"` or `"gpu:N"`. */
      device: string;
      /**
       * Format: int64
       * @description Upper bound this service could grow to on the device. Equals `bytes`
       *     for fixed-size services; larger for a dynamic command service that may
       *     borrow up to its configured maximum.
       */
      max_bytes: number;
      /**
       * Format: int64
       * @description Total memory capacity of the device, in bytes. Zero if unknown.
       */
      total_bytes: number;
      /**
       * Format: int64
       * @description Memory bytes already in use on the device by everything except this
       *     service (for a running service, its own resident memory is excluded so
       *     `used_by_others_bytes + bytes` doesn't double-count it).
       */
      used_by_others_bytes: number;
    };
    /** @description One reservation held against a device. */
    DeviceReservation: {
      /**
       * Format: int64
       * @description Bytes reserved.
       */
      bytes: number;
      /** @description Whether the reservation is elastic (dynamic service borrowing). */
      elastic: boolean;
      /** @description Service holding the reservation. */
      service: string;
    };
    /** @description One device memory sample. */
    DeviceSampleResponse: {
      /** @description Device id (`"gpu:0"`, `"cpu"`, etc.). */
      device: string;
      /**
       * Format: int64
       * @description Free bytes at sample time.
       */
      free_bytes: number;
      /**
       * Format: int64
       * @description Sample timestamp (ms since epoch).
       */
      timestamp_ms: number;
      /**
       * Format: int64
       * @description Total capacity in bytes.
       */
      total_bytes: number;
      /**
       * Format: int64
       * @description Used bytes at sample time.
       */
      used_bytes: number;
    };
    /** @description `GET /api/devices/samples` response body. */
    DeviceSamplesResponse: {
      /** @description Samples ordered by timestamp ascending. */
      samples: components["schemas"]["DeviceSampleResponse"][];
    };
    /** @description One entry in `GET /api/devices`. */
    DeviceSummary: {
      /**
       * Format: int64
       * @description Currently free bytes.
       */
      free_bytes: number;
      /** @description Device id string, e.g. `"gpu:0"` or `"cpu"`. */
      id: string;
      /** @description Human-readable device name. */
      name: string;
      /** @description Per-service reservation breakdown. */
      reservations: components["schemas"]["DeviceReservation"][];
      /**
       * Format: int64
       * @description Total byte capacity.
       */
      total_bytes: number;
    };
    /** @description `POST /api/services/{name}/disable` response body. */
    DisableResponse:
      | {
          /** @enum {string} */
          status: "disabled";
        }
      | {
          /** @enum {string} */
          status: "already_disabled";
        };
    /**
     * @description `POST /v1/embeddings` request envelope.
     *
     *     The daemon only interprets the `model` field; all other keys are
     *     forwarded verbatim to the upstream service.
     */
    EmbeddingEnvelope: {
      [key: string]: unknown;
    } & {
      /** @description Model name (maps to an ananke service name). */
      model: string;
    };
    /** @description `POST /api/services/{name}/enable` response body. */
    EnableResponse:
      | {
          /** @enum {string} */
          status: "enabled";
        }
      | {
          /** @enum {string} */
          status: "not_disabled";
        }
      | {
          /** @enum {string} */
          status: "already_enabled";
        };
    /** @description One environment variable ananke sets on the child process. */
    EnvVar: {
      /** @description Variable name (e.g. `CUDA_VISIBLE_DEVICES`). */
      key: string;
      /** @description Variable value. */
      value: string;
    };
    /**
     * @description Estimator output projected to the wire. Carries the components a
     *     reader needs to answer "how much VRAM will this service take?"
     *     without having to re-derive any of them client-side.
     */
    EstimateSummary: {
      /**
       * Format: int64
       * @description Compute-buffer reservation per active device, in bytes.
       */
      compute_buffer_bytes_per_device: number;
      /**
       * Format: int32
       * @description Configured context window the estimate is sized against.
       */
      configured_context: number;
      /**
       * Format: int64
       * @description `kv_per_token × configured_context`. Precomputed so the
       *     frontend can render the total directly.
       */
      kv_bytes_for_context: number;
      /**
       * Format: int64
       * @description KV cache bytes per context token. Zero for SSM/Mamba
       *     architectures with no KV cache.
       */
      kv_per_token: number;
      /**
       * Format: int64
       * @description Static weight bytes (including mmproj if configured).
       */
      weights_bytes: number;
    };
    /**
     * @description One event delivered over `/api/events`. The `type` tag discriminates the
     *     variant; `at_ms` is present on every variant except `overflow`.
     */
    Event:
      | {
          /** Format: int64 */
          at_ms: number;
          from: string;
          service: string;
          to: string;
          /** @enum {string} */
          type: "state_changed";
        }
      | {
          /** Format: int64 */
          at_ms: number;
          reservations: {
            [key: string]: number;
          };
          service: string;
          /** @enum {string} */
          type: "allocation_changed";
        }
      | {
          /** Format: int64 */
          at_ms: number;
          changed_services: string[];
          /** @enum {string} */
          type: "config_reloaded";
        }
      | {
          /** Format: int64 */
          at_ms: number;
          /** Format: float */
          rolling_mean: number;
          service: string;
          /** @enum {string} */
          type: "estimator_drift";
        }
      | {
          /** Format: int64 */
          at_ms: number;
          detail: string;
          service: string;
          trigger: string;
          /** @enum {string} */
          type: "auto_restarted";
        }
      | {
          /** Format: int64 */
          dropped: number;
          /** @enum {string} */
          type: "overflow";
        };
    /**
     * @description Whether a service's estimated placement fits under current conditions.
     * @enum {string}
     */
    FitVerdict: "fits" | "needs_eviction" | "does_not_fit";
    /**
     * @description The ik_llama.cpp knobs of a `runtime = { kind = "ik-llama", ... }`
     *     service, mirrored from the validated config, plus the fit margins
     *     ananke derives from them (which appear nowhere in the operator's
     *     own config).
     */
    IkParams: {
      /**
       * Format: int32
       * @description `-amb` attention scratch cap in MiB, when set.
       */
      attn_max_batch?: number | null;
      /** @description DSA sparse attention (`-dsa -fidx`). */
      dsa: boolean;
      /** @description Fork-side auto-placement (`--fit`). */
      fit: boolean;
      /**
       * @description The `--gpu-fit-margin` values (MiB) ananke computes and emits
       *     per visible device when `fit` is on: index 0 is the child's
       *     device 0, and so on. Empty when `fit` is off.
       */
      fit_margins_mib?: number[];
      /**
       * Format: int32
       * @description MLA kernel mode (`-mla`, 0-3), when set.
       */
      mla?: number | null;
      /** @description `-rtr` runtime repacking. */
      runtime_repack: boolean;
    };
    /** @description One launch command — argv and environment. */
    LaunchCommand: {
      /**
       * @description The full argv. `argv[0]` is the binary; the rest are its arguments.
       *     Already split into tokens — no shell quoting is applied, so a client
       *     rendering a copy-pasteable line should quote as needed.
       */
      argv: string[];
      /**
       * @description Environment variables ananke sets or overrides for the child (notably
       *     `CUDA_VISIBLE_DEVICES`), sorted by key. Not the full inherited
       *     environment.
       */
      env: components["schemas"]["EnvVar"][];
      /**
       * @description Whether the child process also inherits the daemon's full
       *     environment (`$PATH`, `$HOME`, locale, …) on top of `env`. When
       *     `false`, the child sees only the variables in `env`.
       */
      env_inherit: boolean;
      /**
       * @description Whether the service is running (`running`) or this is a preview of the
       *     next start (`preview`).
       */
      source: components["schemas"]["LaunchCommandSource"];
    };
    /**
     * @description Response from `GET /api/services/{name}/command`: the launch command
     *     computed under two scenarios.
     */
    LaunchCommandResponse: {
      active?: null | components["schemas"]["LaunchCommand"];
      /**
       * @description Command on an empty cluster — what the service would launch with
       *     if no other services held pledges. Always present when the service
       *     can fit on the hardware at all.
       */
      on_empty: components["schemas"]["LaunchCommand"];
    };
    /**
     * @description Whether a [`LaunchCommand`] describes a live process or a what-if.
     * @enum {string}
     */
    LaunchCommandSource: "running" | "preview";
    /** @description One captured stdout/stderr line. */
    LogLine: {
      /** @description The line content (sans trailing newline). */
      line: string;
      /**
       * Format: int64
       * @description Owning run id.
       */
      run_id: number;
      /**
       * Format: int64
       * @description Sequence number within `(service_id, run_id)`, monotonic per run.
       */
      seq: number;
      /** @description `"stdout"` or `"stderr"`. */
      stream: string;
      /**
       * Format: int64
       * @description Millisecond UNIX timestamp the line was received.
       */
      timestamp_ms: number;
    };
    /** @description Frame sent over `/api/services/{name}/logs/stream`. */
    LogStreamMessage:
      | (components["schemas"]["LogLine"] & {
          /** @enum {string} */
          type: "line";
        })
      | {
          /**
           * Format: int64
           * @description Number of dropped frames.
           */
          dropped: number;
          /** @enum {string} */
          type: "overflow";
        };
    /** @description `GET /api/services/{name}/logs` response body. */
    LogsResponse: {
      /** @description Newest-first page of log lines. */
      logs: components["schemas"]["LogLine"][];
      /** @description Opaque cursor for paging further back; `None` when exhausted. */
      next_cursor?: string | null;
    };
    /** @description One time bucket of aggregated request metrics, scoped to a single service. */
    MetricBucketResponse: {
      /**
       * Format: double
       * @description Average request duration in milliseconds, if any requests had timing data.
       */
      avg_duration_ms?: number | null;
      /**
       * Format: double
       * @description Average time-to-first-token in milliseconds (streaming requests only).
       */
      avg_ttft_ms?: number | null;
      /**
       * Format: int64
       * @description Start of the bucket (ms since epoch).
       */
      bucket_start: number;
      /**
       * Format: int64
       * @description Total completion tokens across all requests in the bucket.
       */
      completion_tokens: number;
      /**
       * Format: double
       * @description End-to-end effective generation throughput: completion tokens divided
       *     by total wall-clock duration, so prefill, TTFT, and queue wait all
       *     count against it. Available whenever the bucket has any request with a
       *     recorded duration, including non-streaming requests with no engine
       *     timings where no decode window exists to derive `output_tps`. Always
       *     ≤ `output_tps`; the UI surfaces it as the fallback line and as the
       *     end-to-end figure. A bucket that generated no tokens (e.g. only
       *     embeddings or stalled requests) is `null`, not zero.
       */
      effective_tps?: number | null;
      /**
       * Format: int64
       * @description Number of requests with a 4xx/5xx status code.
       */
      error_count: number;
      /**
       * Format: double
       * @description Input tokens per second during prompt processing: prompt tokens
       *     divided by total TTFT. `None` if no timed requests in the bucket.
       */
      input_tps?: number | null;
      /**
       * Format: double
       * @description Output tokens per second during decode: completion tokens divided by
       *     total decode time. `None` if no timed requests in the bucket.
       */
      output_tps?: number | null;
      /**
       * Format: int64
       * @description Total prompt tokens across all requests in the bucket.
       */
      prompt_tokens: number;
      /**
       * Format: int64
       * @description Number of requests in the bucket.
       */
      request_count: number;
      /**
       * @description Service name these metrics belong to. `None` if the service has been
       *     deleted from the database but metric rows remain.
       */
      service?: string | null;
    };
    /** @description `GET /api/metrics` response body. */
    MetricsResponse: {
      /** @description Time-series buckets, ordered by `bucket_start` ascending. */
      buckets: components["schemas"]["MetricBucketResponse"][];
    };
    /**
     * @description What kind of model the service exposes through the OpenAI-compatible
     *     API. Drives badge rendering in the frontend and lets clients (Discord
     *     rotation, RAG indexers) filter the model list by purpose without
     *     parsing `metadata.*` strings.
     *
     *     Defaults to `Chat` so existing configs and JSON payloads stay
     *     byte-identical — the field is elided from the wire when it's `Chat`.
     * @enum {string}
     */
    Modality: "chat" | "embedding";
    /**
     * @description GGUF-derived facts about a model file. Read once per service per
     *     daemon run and cached; the file isn't re-parsed on every detail
     *     poll.
     */
    ModelInfo: {
      /**
       * @description `general.architecture` from the GGUF (`"qwen2"`, `"llama"`,
       *     `"qwen3moe"`, …).
       */
      architecture: string;
      /**
       * Format: int32
       * @description Layer count exposed by the architecture's `{arch}.block_count`
       *     metadata key, when present.
       */
      block_count?: number | null;
      /**
       * @description File name (basename of shard 0). Useful for the UI to show the
       *     underlying filename without the full path.
       */
      file_name: string;
      /**
       * @description `true` when the service has a configured `mmproj` GGUF — the
       *     standard signal for vision / multimodal support.
       */
      has_mmproj: boolean;
      /**
       * @description `general.license` if declared (`"apache-2.0"`, `"llama3.3"`,
       *     `"gemma"`, …). Surfaced so operators can see the licence
       *     without leaving the dashboard.
       */
      license?: string | null;
      /**
       * @description Friendly name declared in `general.name`, when the publisher
       *     set one. Typically the upstream model identifier ("Qwen3 32B",
       *     "Llama 3.3 70B Instruct", …) rather than ananke's service
       *     name. Absent for hand-built GGUFs that left the field blank.
       */
      model_name?: string | null;
      /**
       * Format: int64
       * @description `general.parameter_count` if declared by the publisher. Modern
       *     converter tools (Unsloth, bartowski's repacks, …) write this;
       *     older GGUFs may not. The field is the model's *parameter*
       *     count, not the on-disk byte size — quantisation makes the two
       *     diverge by a large factor.
       */
      parameter_count?: number | null;
      /**
       * Format: int32
       * @description Number of shards discovered. 1 for a single-file GGUF.
       */
      shard_count: number;
      /**
       * Format: int64
       * @description Sum of every tensor's byte size across every shard. The
       *     reference number when sizing the model on disk.
       */
      total_tensor_bytes: number;
      /**
       * Format: int32
       * @description The model's *trained* context window, read from
       *     `{arch}.context_length`. The service's configured context may
       *     be lower.
       */
      trained_context_length?: number | null;
    };
    /** @description One entry in the `GET /v1/models` response. */
    ModelListing: {
      /**
       * @description Passthrough entries from `[[service]] metadata.*`. Non-standard
       *     OpenAI field, elided when empty; strict OpenAI clients ignore it.
       */
      ananke_metadata?: Record<string, never>;
      /**
       * Format: int64
       * @description Creation timestamp (always 0 for ananke-managed models).
       */
      created: number;
      /** @description Model id (the service name). */
      id: string;
      /**
       * @description What kind of OpenAI endpoint this model serves. Non-standard
       *     OpenAI field, elided when [`Modality::Chat`] (the default), so
       *     strict OpenAI clients see exactly what they saw before this
       *     field landed; embedding clients can filter on it.
       */
      modality?: components["schemas"]["Modality"];
      /** @description Always `"model"`. */
      object: string;
      /** @description Always `"ananke"`. */
      owned_by: string;
    };
    /** @description `GET /v1/models` response body. */
    ModelsResponse: {
      /** @description Available models. */
      data: components["schemas"]["ModelListing"][];
      /** @description Always `"list"`. */
      object: string;
    };
    /** @description Allocation-mode knobs for [`OneshotRequest`]. */
    OneshotAllocation: {
      /**
       * Format: float
       * @description Dynamic max.
       */
      max_vram_gb?: number | null;
      /**
       * Format: float
       * @description Dynamic min.
       */
      min_vram_gb?: number | null;
      /** @description `"static"` or `"dynamic"`; `None` for llama-cpp template. */
      mode?: string | null;
      /**
       * Format: float
       * @description Static allocation amount.
       */
      vram_gb?: number | null;
    };
    /** @description Device-placement hints for [`OneshotRequest`]. */
    OneshotDevices: {
      /** @description `"gpu-only"` / `"cpu-only"` / `"hybrid"`. */
      placement?: string | null;
    };
    /** @description Health-check configuration for a oneshot. */
    OneshotHealth: {
      /** @description HTTP path to probe (e.g. `"/health"`, `"/system_stats"`). */
      http: string;
      /** @description Probe interval duration string. Defaults to 5 seconds. */
      probe_interval?: string | null;
      /** @description Timeout duration string (e.g. `"30s"`, `"2m"`). Defaults to 3 minutes. */
      timeout?: string | null;
    };
    /** @description `POST /api/oneshot` request body. */
    OneshotRequest: {
      /** @description Allocation mode + sizes. */
      allocation: components["schemas"]["OneshotAllocation"];
      /** @description Command + args for the `"command"` template. */
      command?: string[] | null;
      devices?: null | components["schemas"]["OneshotDevices"];
      health?: null | components["schemas"]["OneshotHealth"];
      /** @description Free-form metadata passed through to responses. */
      metadata?: {
        [key: string]: unknown;
      };
      /** @description Optional human-meaningful name; daemon auto-generates if absent. */
      name?: string | null;
      /**
       * Format: int32
       * @description Explicit port request; `None` means daemon picks from the pool.
       */
      port?: number | null;
      /**
       * Format: int32
       * @description Eviction priority.
       */
      priority?: number | null;
      /** @description `"llama-cpp"` or `"command"`. */
      template: string;
      /** @description Time-to-live duration string (`"2h"`, `"30m"`). */
      ttl?: string | null;
      /** @description Working directory for the spawned child. */
      workdir?: string | null;
    };
    /** @description `POST /api/oneshot` response body. */
    OneshotResponse: {
      /** @description ULID identifier (prefixed `oneshot_`). */
      id: string;
      /** @description Path component suitable for appending to `ANANKE_ENDPOINT` to open the log stream. */
      logs_url: string;
      /** @description Assigned name. */
      name: string;
      /**
       * Format: int32
       * @description Bound port.
       */
      port: number;
    };
    /**
     * @description `GET /api/oneshot/{id}` response body. Also used by `GET /api/oneshot`
     *     (which returns `Vec<OneshotStatus>`).
     */
    OneshotStatus: {
      /**
       * Format: int64
       * @description End timestamp, if terminal.
       */
      ended_at_ms?: number | null;
      /**
       * Format: int32
       * @description Exit code when the child terminated with one.
       */
      exit_code?: number | null;
      /** @description ULID id. */
      id: string;
      /** @description Path component for the WS log-stream endpoint. */
      logs_url: string;
      /** @description Name. */
      name: string;
      /**
       * Format: int32
       * @description Port.
       */
      port: number;
      /**
       * Format: int64
       * @description Start timestamp, if reached Running.
       */
      started_at_ms?: number | null;
      /** @description Current state (`"pending"`, `"running"`, `"ended"`, `"evicted"`, etc.). */
      state: string;
      /**
       * Format: int64
       * @description Submission timestamp.
       */
      submitted_at_ms: number;
    };
    /**
     * @description Where a service's memory would land per device under current conditions, and
     *     whether it fits without the daemon having to evict or reclaim. Computed by
     *     running the placement engine against the live snapshot and pledge book.
     */
    PlacementPreview: {
      /**
       * @description Per-device memory the service would occupy, sorted by device. Keys are
       *     slot strings (`"cpu"`, `"gpu:0"`, …); values are bytes.
       */
      devices: components["schemas"]["DevicePlacement"][];
      /**
       * Format: int64
       * @description Total expert-tensor bytes the packer offloaded to the CPU for a MoE
       *     model (auto/manual `expert_offload`). Zero for non-MoE services or when
       *     nothing was offloaded.
       */
      expert_offload_bytes: number;
      /**
       * Format: int32
       * @description Number of distinct layers with at least one expert offloaded to the CPU.
       */
      expert_offload_layers: number;
      /** @description Whether the placement fits right now without eviction or reclaim. */
      verdict: components["schemas"]["FitVerdict"];
    };
    /**
     * @description Which llama-server implementation serves a llama-cpp service, plus
     *     the fork-specific configuration when it is not mainline.
     */
    RuntimeInfo: {
      ik?: null | components["schemas"]["IkParams"];
      /** @description `"llama-cpp"` (mainline) or `"ik-llama"` (ikawrakow fork). */
      kind: string;
    };
    /** @description `GET /api/services/{name}` response body. */
    ServiceDetail: {
      /**
       * @description Passthrough entries from `[[service]] metadata.*`. See
       *     [`crate::services::list::ServiceSummary::ananke_metadata`].
       */
      ananke_metadata?: Record<string, never>;
      /**
       * @description What pledge the service is currently holding on each device.
       *     Empty when idle. Keys are slot strings (`"cpu"`, `"gpu:0"`, …),
       *     values are MiB.
       */
      current_allocation: {
        [key: string]: number;
      };
      /** @description Placeholder for elastic-borrower tracking. */
      elastic_borrower?: string | null;
      estimate?: null | components["schemas"]["EstimateSummary"];
      /**
       * Format: int64
       * @description Idle-before-drain timeout.
       */
      idle_timeout_ms: number;
      /**
       * Format: int64
       * @description Wall-clock timestamp (ms since epoch) of the last time the
       *     service was provisioned or received a request. `None` if the
       *     service has never been started.
       */
      last_used_ms?: number | null;
      /** @description `"persistent"` or `"ondemand"`. */
      lifecycle: string;
      /**
       * @description What kind of OpenAI endpoint the service serves. See
       *     [`crate::services::list::ServiceSummary::modality`] for the rendering rule.
       */
      modality?: components["schemas"]["Modality"];
      model_info?: null | components["schemas"]["ModelInfo"];
      /** @description Service name. */
      name: string;
      /**
       * Format: int64
       * @description Observed memory peak (VRAM + RSS) across the service's lifetime.
       */
      observed_peak_bytes: number;
      /**
       * Format: int32
       * @description Child PID if any.
       */
      pid?: number | null;
      /** @description Manual placement override, keyed by device slot string. */
      placement_override: {
        [key: string]: number;
      };
      placement_preview?: null | components["schemas"]["PlacementPreview"];
      /**
       * Format: int32
       * @description Public port.
       */
      port: number;
      /**
       * Format: int32
       * @description Eviction priority.
       */
      priority: number;
      /**
       * Format: int32
       * @description Private (upstream) port.
       */
      private_port: number;
      /** @description Most recent log lines for a frontend's first-paint context. */
      recent_logs: components["schemas"]["LogLine"][];
      /**
       * Format: float
       * @description Rolling estimator correction factor.
       */
      rolling_mean?: number | null;
      /**
       * Format: int64
       * @description Sample count backing the rolling mean.
       */
      rolling_samples: number;
      /**
       * Format: int64
       * @description Active run id if any.
       */
      run_id?: number | null;
      runtime?: null | components["schemas"]["RuntimeInfo"];
      serving?: null | components["schemas"]["ServingConfig"];
      /** @description Current state name. */
      state: string;
      /** @description Template name, e.g. `"llamacpp"` or `"command"`. */
      template: string;
    };
    /** @description One entry in `GET /api/services`. */
    ServiceSummary: {
      /**
       * @description Passthrough entries from `[[service]] metadata.*`. Empty when
       *     none were set; the field is elided from JSON when the map is
       *     empty so existing consumers see no change unless a service opts
       *     in to metadata.
       */
      ananke_metadata?: Record<string, never>;
      /** @description Placeholder for elastic-borrower tracking (future work). */
      elastic_borrower?: string | null;
      fit_verdict?: null | components["schemas"]["FitVerdict"];
      /**
       * @description `true` when the service's `[[service.llama_cpp]]` config has a
       *     `mmproj` entry — the standard signal that it supports vision /
       *     multimodal input. `None` for non-llama-cpp services. Cheap
       *     enough (config-only check) to ship on every list entry.
       */
      has_mmproj?: boolean | null;
      /**
       * Format: int64
       * @description Number of requests currently in flight through the proxy for this
       *     service. Zero when the service is not running.
       */
      inflight_count?: number;
      /**
       * Format: int64
       * @description Wall-clock timestamp (ms since epoch) of the last time the
       *     service was provisioned or received a request. `None` if the
       *     service has never been started.
       */
      last_used_ms?: number | null;
      /** @description `"persistent"` or `"ondemand"`. */
      lifecycle: string;
      /**
       * @description What kind of OpenAI endpoint the service serves. Elided from
       *     JSON when [`Modality::Chat`] (the default) so existing chat
       *     services emit unchanged wire bytes; embedding services explicitly
       *     declare `modality = "embedding"` in their `[[service]]` block.
       */
      modality?: components["schemas"]["Modality"];
      /** @description Service name (matches `[[service]]` table in config). */
      name: string;
      /**
       * Format: int32
       * @description Child PID if currently running.
       */
      pid?: number | null;
      /**
       * Format: int32
       * @description Public port the proxy listens on.
       */
      port: number;
      /**
       * Format: int32
       * @description Eviction priority.
       */
      priority: number;
      /**
       * Format: int64
       * @description Active run id if currently running.
       */
      run_id?: number | null;
      /** @description State like `"idle"`, `"running"`, `"disabled_user_disabled"`. */
      state: string;
      /**
       * Format: int64
       * @description Total VRAM bytes the service would reserve across all devices
       *     under current conditions (from the placement preview). Includes
       *     weights, KV cache, and compute buffer. `None` when the placement
       *     can't be computed (e.g. a command service that reserves no VRAM).
       */
      vram_bytes?: number | null;
    };
    /** @description Response from `GET /api/services`. */
    ServicesResponse: {
      /**
       * Format: int32
       * @description Port the OpenAI-compatible API is listening on.
       */
      openai_api_port: number;
      /** @description Registered services. */
      services: components["schemas"]["ServiceSummary"][];
    };
    /**
     * @description Curated serving configuration for a llama-cpp service: the knobs an
     *     operator reaches for when comparing services or debugging
     *     performance, plus derived values (per-slot context) that no single
     *     config key or argv flag states directly.
     */
    ServingConfig: {
      /**
       * Format: int32
       * @description Logical batch size (`-b`), when set.
       */
      batch_size?: number | null;
      /**
       * @description The llama-server executable path serving this service. With
       *     multiple runtimes installed (mainline + ik_llama), which binary
       *     a service uses is a first-class fact.
       */
      binary: string;
      /** @description KV cache type for keys (`f16` when unset). */
      cache_type_k: string;
      /** @description KV cache type for values (`f16` when unset). */
      cache_type_v: string;
      /**
       * @description Draft model file name (not full path), when a separate draft
       *     GGUF is configured.
       */
      draft_model?: string | null;
      /**
       * Format: int32
       * @description The context window a single request actually gets: `context`
       *     divided by `parallel` when the KV pool is statically split,
       *     or the full window when unified (slots borrow from each other).
       */
      effective_context_per_slot?: number | null;
      /** @description MoE expert-offload mode: `"off"`, `"auto"`, or a layer count. */
      expert_offload: string;
      /** @description Flash attention enabled. */
      flash_attn: boolean;
      /** @description Unified KV pool across slots (`--kv-unified`). */
      kv_unified: boolean;
      /** @description Model locked in RAM (`--mlock`). */
      mlock: boolean;
      /** @description Model file memory-mapped (llama.cpp's default is `true`). */
      mmap: boolean;
      /** @description `--numa` strategy, when set. */
      numa?: string | null;
      /**
       * Format: int32
       * @description Request parallelism (`-np`).
       */
      parallel: number;
      /** @description `--spec-type` value, when speculative decoding is on. */
      spec_type?: string | null;
      /**
       * Format: int32
       * @description Generation threads (`-t`), when set.
       */
      threads?: number | null;
      /**
       * Format: int32
       * @description Prompt-processing threads (`-tb`), when set.
       */
      threads_batch?: number | null;
      /**
       * Format: int32
       * @description Physical batch size (`-ub`), when set.
       */
      ubatch_size?: number | null;
    };
    /** @description `POST /api/services/{name}/start` response body. */
    StartResponse:
      | {
          /** @enum {string} */
          status: "already_running";
        }
      | {
          /** Format: int64 */
          run_id: number;
          /** @enum {string} */
          status: "started";
        }
      | {
          /** @enum {string} */
          status: "queue_full";
        }
      | {
          error: components["schemas"]["ApiErrorBody"];
          /** @enum {string} */
          status: "unavailable";
        };
    /** @description `POST /api/services/{name}/stop` response body. */
    StopResponse:
      | {
          /** @enum {string} */
          status: "not_running";
        }
      | {
          /** @enum {string} */
          status: "drained";
        };
    /** @description One validation error from the config parser. */
    ValidationError: {
      /**
       * Format: int32
       * @description 1-based column number in the TOML source.
       */
      column: number;
      /**
       * Format: int32
       * @description 1-based line number in the TOML source.
       */
      line: number;
      /** @description Human-readable message. */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
    };
  };
  put_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Raw TOML config */
    requestBody: {
      content: {
        "text/plain": string;
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description hash_mismatch */
      412: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigValidateResponse"];
        };
      };
      /** @description if_match_required */
      428: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description persist_failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_validate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigValidateRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigValidateResponse"];
        };
      };
    };
  };
  list_devices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceSummary"][];
        };
      };
    };
  };
  get_device_samples: {
    parameters: {
      query?: {
        /** @description Filter to one device (e.g. "gpu:0", "cpu") */
        device?: string;
        /** @description Earliest timestamp_ms (default: 1h ago) */
        since?: number;
        /** @description Latest timestamp_ms (default: now) */
        until?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceSamplesResponse"];
        };
      };
    };
  };
  get_info: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DaemonInfoResponse"];
        };
      };
    };
  };
  get_metrics: {
    parameters: {
      query?: {
        /** @description Filter to one service name */
        service?: string;
        /** @description Earliest timestamp_ms, inclusive (default: 1h ago) */
        since?: number;
        /** @description Latest timestamp_ms, inclusive (default: now) */
        until?: number;
        /** @description Bucket size: "1m", "5m", "1h" (default: "5m") */
        bucket?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricsResponse"];
        };
      };
      /** @description invalid_request_error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_oneshots: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OneshotStatus"][];
        };
      };
    };
  };
  post_oneshot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OneshotRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OneshotResponse"];
        };
      };
      /** @description invalid_request_error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description start_failed, start_queue_full */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_oneshot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OneshotStatus"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  delete_oneshot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_services: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServicesResponse"];
        };
      };
    };
  };
  service_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceDetail"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  service_command: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LaunchCommandResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description insufficient_vram */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_disable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DisableResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_enable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnableResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_logs: {
    parameters: {
      query?: {
        /** @description Earliest timestamp_ms, inclusive */
        since?: number;
        /** @description Latest timestamp_ms, inclusive */
        until?: number;
        /** @description Restrict to one run_id */
        run?: number;
        /** @description "stdout" or "stderr" */
        stream?: string;
        /** @description Max rows to return (≤1000, default 200) */
        limit?: number;
        /** @description Opaque cursor from a prior response */
        before?: string;
      };
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogsResponse"];
        };
      };
      /** @description invalid_cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_restart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_disabled, start_queue_full, start_failed, insufficient_vram, service_blocked */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_start: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_disabled, start_queue_full, start_failed, insufficient_vram, service_blocked */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  post_stop: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StopResponse"];
        };
      };
      /** @description service_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  chat_completions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatCompletionEnvelope"];
      };
    };
    responses: {
      /** @description Proxied from upstream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description invalid_request_error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description model_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description upstream_unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_disabled, start_queue_full, start_failed, insufficient_vram, service_blocked */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  completions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompletionEnvelope"];
      };
    };
    responses: {
      /** @description Proxied from upstream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description invalid_request_error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description model_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description upstream_unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_disabled, start_queue_full, start_failed, insufficient_vram, service_blocked */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  embeddings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmbeddingEnvelope"];
      };
    };
    responses: {
      /** @description Proxied from upstream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description invalid_request_error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description model_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description upstream_unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description service_disabled, start_queue_full, start_failed, insufficient_vram, service_blocked */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_models: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelsResponse"];
        };
      };
    };
  };
}
