//! Aggregated OpenAPI document for the daemon.

use ananke_api::{
    config::{
        get::ConfigResponse,
        validate::{ConfigValidateRequest, ConfigValidateResponse, ValidationError},
    },
    devices::{
        list::{DeviceReservation, DeviceSummary},
        samples::{DeviceSampleResponse, DeviceSamplesResponse},
    },
    events::Event,
    info::get::DaemonInfoResponse,
    internal::{fit_verdict::FitVerdict, log_line::LogLine},
    metrics::get::{MetricBucketResponse, MetricsResponse},
    oneshot::{
        create::{
            OneshotAllocation, OneshotDevices, OneshotHealth, OneshotRequest, OneshotResponse,
        },
        get::OneshotStatus,
    },
    openai::{
        ChatCompletionEnvelope, CompletionEnvelope, EmbeddingEnvelope, ModelListing, ModelsResponse,
    },
    services::{
        command::{LaunchCommand, LaunchCommandResponse, LaunchCommandSource},
        detail::{DevicePlacement, PlacementPreview, ServiceDetail},
        disable::DisableResponse,
        enable::EnableResponse,
        list::{ServiceSummary, ServicesResponse},
        logs::LogsResponse,
        logs_stream::LogStreamMessage,
        start::StartResponse,
        stop::StopResponse,
    },
    shared::{
        errors::{ApiError, ApiErrorCodeSlug, ApiErrorKind},
        modality::Modality,
    },
};
use axum::{
    Json,
    extract::State,
    response::{IntoResponse, Response},
    routing::{Router, get},
};
use utoipa::OpenApi;

use crate::{
    api::{
        management::{
            config as mgmt_config, handlers as mgmt_handlers, info as mgmt_info,
            lifecycle as mgmt_lifecycle, logs as mgmt_logs, metrics as mgmt_metrics,
        },
        openai::handlers as openai_handlers,
    },
    daemon::app_state::AppState,
    oneshot::handlers as oneshot_handlers,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        openai_handlers::list_models,
        openai_handlers::chat_completions,
        openai_handlers::completions,
        openai_handlers::embeddings,
        mgmt_handlers::list_services,
        mgmt_handlers::service_detail,
        mgmt_handlers::service_command,
        mgmt_handlers::list_devices,
        mgmt_info::get_info,
        mgmt_lifecycle::post_start,
        mgmt_lifecycle::post_stop,
        mgmt_lifecycle::post_restart,
        mgmt_lifecycle::post_enable,
        mgmt_lifecycle::post_disable,
        mgmt_logs::get_logs,
        mgmt_config::get_config,
        mgmt_config::put_config,
        mgmt_config::post_validate,
        mgmt_metrics::get_metrics,
        mgmt_metrics::get_device_samples,
        oneshot_handlers::post_oneshot,
        oneshot_handlers::list_oneshots,
        oneshot_handlers::get_oneshot,
        oneshot_handlers::delete_oneshot,
    ),
    components(schemas(
        ModelListing,
        ModelsResponse,
        ChatCompletionEnvelope,
        CompletionEnvelope,
        EmbeddingEnvelope,
        ananke_api::shared::errors::ApiError,
        ApiErrorCodeSlug,
        ApiErrorKind,
        ServiceSummary,
        ServicesResponse,
        ServiceDetail,
        PlacementPreview,
        DevicePlacement,
        FitVerdict,
        LaunchCommand,
        LaunchCommandResponse,
        LaunchCommandSource,
        LogLine,
        LogsResponse,
        LogStreamMessage,
        DeviceSummary,
        DeviceReservation,
        StartResponse,
        StopResponse,
        EnableResponse,
        DisableResponse,
        ConfigResponse,
        ConfigValidateRequest,
        ConfigValidateResponse,
        ValidationError,
        MetricsResponse,
        MetricBucketResponse,
        DeviceSamplesResponse,
        DeviceSampleResponse,
        DaemonInfoResponse,
        ApiError,
        OneshotRequest,
        OneshotAllocation,
        OneshotDevices,
        OneshotHealth,
        OneshotResponse,
        OneshotStatus,
        Modality,
        Event,
        // Per-endpoint error types generated by `endpoint_error!`.
    )),
    info(title = "Ananke API", version = "0.1.0")
)]
pub struct AnankeApi;

pub fn register(router: Router, state: AppState) -> Router {
    let openapi: Router = Router::new()
        .route("/api/openapi.json", get(serve_openapi))
        .with_state(state);
    router.merge(openapi)
}

pub async fn serve_openapi(State(_state): State<AppState>) -> Response {
    (axum::http::StatusCode::OK, Json(AnankeApi::openapi())).into_response()
}
