[package]
name = "ananke-db"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "ananke_db"
path = "src/lib.rs"

[dependencies]
ananke-api.workspace = true
ananke-errors.workspace = true
ananke-time.workspace = true
parking_lot.workspace = true
nix.workspace = true
rusqlite.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }