//! Ananke — GPU/CPU-aware model proxy daemon.

pub mod activity;
pub mod allocator;
pub mod app_state;
pub mod config;
pub mod daemon;
pub mod drain;
pub mod eviction;
pub mod db;
pub mod devices;
pub mod errors;
pub mod estimator;
pub mod gguf;
pub mod inflight;
pub mod management_api;
pub mod observation;
pub mod openai_api;
pub mod openapi;
pub mod placement;
pub mod proxy;
pub mod retention;
pub mod rolling;
pub mod service_registry;
pub mod signals;
pub mod snapshotter;
pub mod state;
pub mod supervise;
pub mod templates;
